In [1]:
import numpy as np

In [11]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
# Get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [14]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [15]:
# Get type
print(a.dtype)
print(b.dtype)

int32
float64


You can see that the 'a' array is 32 bits (4 bytes), we can change the size of this array to 16 bits (2 bytes).

In [17]:
a = np.array([1,2,3], dtype='int16')

We can now check the 'dtype' and see it has successfully reduced in size.

In [18]:
print(a.dtype)

int16


In [23]:
# Get size
print(a.itemsize, "bytes")
print(b.itemsize, "bytes")

2 bytes
8 bytes


In [24]:
# Get total size
print(a.size * a.itemsize, "bytes")
print(a.nbytes, "bytes")

6 bytes
6 bytes


Accessing // Changing specific elemts, rows, columns, etc.

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# Get specific element [r,c]
print(a[1, 5])
print(a[1, -2])

13
13


In [30]:
# Get a specific row
print(a[0, :])

[1 2 3 4 5 6 7]


In [31]:
# Get a specific column
print(a[:, 2])

[ 3 10]


In [33]:
# Complex accessing [startindex : endindex : stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [35]:
# Change single items
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [36]:
# Change multiple items with a single item
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [38]:
# Change multiple items with multiple items
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [41]:
# 3D example
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# Get specific single element (work outside in). Say I want '4'
b[0,1,1]
# 0 - the top section
# 1 - the second row
# 1 - the second item in the second row

4

In [46]:
# Get specific multiple elements
b[:,1,:]
# : - all of sections
# 1 - the second row
# : - all of the items in the second row

array([[3, 4],
       [7, 8]])

In [ ]:
# https://www.youtube.com/watch?v=GPVsHOlRBBI
# Data analysis with Python / Numpy / Pandas / Data Viz