In [1]:
import numpy as np

In [11]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
# Get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [14]:
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [15]:
# Get type
print(a.dtype)
print(b.dtype)

int32
float64


You can see that the 'a' array is 32 bits (4 bytes), we can change the size of this array to 16 bits (2 bytes).

In [17]:
a = np.array([1,2,3], dtype='int16')

We can now check the 'dtype' and see it has successfully reduced in size.

In [18]:
print(a.dtype)

int16


In [23]:
# Get size
print(a.itemsize, "bytes")
print(b.itemsize, "bytes")

2 bytes
8 bytes


In [24]:
# Get total size
print(a.size * a.itemsize, "bytes")
print(a.nbytes, "bytes")

6 bytes
6 bytes


Accessing // Changing specific elemts, rows, columns, etc.

In [7]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# Get specific element [r,c]
print(a[1, 5])
print(a[1, -2])

13
13


In [30]:
# Get a specific row
print(a[0, :])

[1 2 3 4 5 6 7]


In [31]:
# Get a specific column
print(a[:, 2])

[ 3 10]


In [9]:
# Complex accessing [startindex : endindex : stepsize]
a[0, 1:5:2]

array([2, 4])

In [35]:
# Change single items
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [36]:
# Change multiple items with a single item
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [38]:
# Change multiple items with multiple items
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [41]:
# 3D example
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# Get specific single element (work outside in). Say I want '4'
b[0,1,1]
# 0 - the top section
# 1 - the second row
# 1 - the second item in the second row

4

In [46]:
# Get specific multiple elements
b[:,1,:]
# : - all of sections
# 1 - the second row
# : - all of the items in the second row

array([[3, 4],
       [7, 8]])

In [ ]:
# https://www.youtube.com/watch?v=GPVsHOlRBBI
# Data analysis with Python / Numpy / Pandas / Data Viz

In [7]:
# All 0's matrix
np.zeros((2,3), dtype='int16')

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [8]:
# All 1's matrix
np.ones((4,2,3), dtype='int16')

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [9]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [12]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [14]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.28520251, 0.09613039],
       [0.00610715, 0.27754085],
       [0.38108345, 0.49197594],
       [0.03017761, 0.24926386]])

In [47]:
# Random integer values
np.random.randint(1,6, size=(3,3))

array([[1, 4, 4],
       [1, 2, 4],
       [4, 5, 3]])

In [50]:
# Make a square matrix. 
# 'identity' is by its nature a square (Linear algebra)
np.identity(5, dtype='int16')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int16)

In [52]:
# Repeat an vector
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [54]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [55]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


[1][1][1][1][1]
[1][0][0][0][1]
[1][0][9][0][1]
[1][0][0][0][1]
[1][1][1][1][1]

Challenge, initialize this matrix by what we have learned.

In [87]:
import numpy as np
c = np.identity(5, dtype='int16')
print(c)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [93]:
c[0, :] = 1
c[-1, :] = 1
c[:, 0] = 1
c[:, -1] = 1
print(c)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [94]:
c[2, 2] = 9
print(c)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [95]:
c[1, 1] = 0
c[3, 3] = 0
print(c)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [98]:
# His solution
output = np.ones((5,5), dtype='int16')
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [100]:
z = np.zeros((3,3), dtype='int16')
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [102]:
z[1,1] = 9
print(z)

[[0 0 0]
 [0 9 0]
 [0 0 0]]


In [104]:
output[1:4, 1:4] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [108]:
# Total solution
output = np.ones((5,5), dtype='int16')
z = np.zeros((3,3), dtype='int16')
z[1,1] = 9
output[1:4, 1:4] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful! #####

In [3]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [110]:
b[0] = 100
print(b)

[100   2   3]


In [114]:
print(a)

# See here that 'b' is just pointing exactly as the thing 'a' is pointing at.
# If you want to avoid that you have to use copy()
a = np.array([1,2,3])
b = a.copy()
print(a)

[100   2   3]
[1 2 3]


#### Mathematics

In [3]:
a = np.array([1,2,3,4])
print(a + 2)
print(a / 2)
print(a - 2)
print(a * 2)

[3 4 5 6]
[0.5 1.  1.5 2. ]
[-1  0  1  2]
[2 4 6 8]


In [4]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [5]:
a ** 2

array([ 1,  4,  9, 16])

In [8]:
# Take sin
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [9]:
# can find the rest of math stuffs here: https://docs.scipy.org/doc/numpy/reference/routines.math.html

#### Linear Algebra

In [16]:
a = np.ones((2,3), dtype='int32')
print(a)
b = np.full((3,2), 2)
print(b)

np.matmul(a, b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [19]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [20]:
# can find the rest of linear math stuffs here: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html
# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc

#### Statistics

In [23]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.min(stats) # Whole matrix
np.min(stats, axis=0) # Column
np.min(stats, axis=1) # Row

array([1, 4])

In [25]:
np.max(stats)

6

In [30]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
b = np.max(a, axis=1).sum()

In [31]:
print(b)

15


#### Reorganizing Arrays

In [36]:
before = np.array([[1,2,3,4],[6,7,8,9]])

print(before)
print("\n")
after = before.reshape((8,1))
print(after)
print("\n")
after = before.reshape((4,2))
print(after)
print("\n")
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [6 7 8 9]]


[[1]
 [2]
 [3]
 [4]
 [6]
 [7]
 [8]
 [9]]


[[1 2]
 [3 4]
 [6 7]
 [8 9]]


[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]


In [40]:
# Vertical stacks
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2,v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
# Horizontal stacks
v1 = np.array([1,2])
v2 = np.array([5,6])

print(np.hstack([v1, v2]))
print(np.hstack((v1, v2)))

[1 2 5 6]
[1 2 5 6]


## Miscellaneous
#### Load data from file

In [ ]:
# Grab data from txt file
# ',' is the separator of all the numbered from this imaginary txt file full of numbers
filedata = np.genfromtxt('file.txt', delimiter=',')
filedata.atype('int32')
filedata

In [ ]:
# Boolean masking and advanced indexing
filedata > 50
